# Generated by Django 6.0 on 2025-12-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexApp', '0002_abilities_pokemon_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
