# Generated by Django 6.0 on 2025-12-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexApp', '0003_pokemon_height_pokemon_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abilities',
            old_name='abilities',
            new_name='name',
        ),
    ]
