# Generated by Django 6.0 on 2025-12-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexApp', '0004_rename_abilities_abilities_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Abilities',
            new_name='Ability',
        ),
    ]
